# 파일 경로: /grl-vote-app/netlify.toml

# Netlify에게 웹사이트로 배포할 파일이 'public' 폴더에 있다고 알려줍니다.
[build]
  publish = "public"

# Netlify에게 '모든 경로(*)'의 요청을 'vote-broadcaster' 엣지 함수로 보내라고 지시합니다.
# 함수 내부 로직에 따라 /vote.html 같은 정적 파일 요청은 정상적으로 처리됩니다.
[[edge_functions]]
  path = "/*"
  function = "vote-broadcaster"